version: "3.8"

services:
  csmart-kakaotalk:
    build: .
    container_name: csmart-kakaotalk-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      # 로그 디렉토리 마운트
      - ./logs:/app/logs
      # Playwright 브라우저 데이터 마운트 (선택사항)
      - playwright-data:/app/playwright-data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  playwright-data:
